# Generated by Django 5.2.3 on 2025-06-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="credits",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
